### ISSUE TITLE
Reply in promise is original message

### ISSUE THREAD

**Issue by buob** [slackhq/node-slack-sdk#243]
I'm not sure if I'm just interpreting this feature incorrectly, but I'm trying to get the response to a message from my bot.

For example, if I send the following message to my slack user and use a promise to wait for the reply...

```js
rtm.sendMessage('yo', dm.id).then((reply) => {
    console.log(reply);
});
```

... what is consoled is the original message:

```js
{ type: 'message',
  channel: 'D1MSL1NP7',
  user: 'U1MSL09SR',
  text: 'yo',
  ts: '1467836576.000093' }
```

Looking at [this PR](https://github.com/slackhq/node-slack-sdk/pull/164) I would have expected it to not console anything, and log a message when the slack user responds to the `yo` message (but it doesn't console anything when the slack user responds).  Am I just wrong about the intent of that promise?  I'm having a hard time finding stuff about the `reply_to` functionality.

_(full repo reproducing the problem [here](https://github.com/buob/node-slack-sdk-replies-test))_

Thanks for the help!

**Comment by DEGoodmanWilson** [comment]
That seems clearly wrong to me as well.

Quick question: Does it work as expected when you use callbacks instead of promises?

**Comment by buob** [comment]
Actually, it just consoles `null` each time.

On second glance, I didn't know if the promise was once the message was actually delivered, which would make a little more sense.  If so, I might just not know how to access `reply_to` stuff.

**Comment by DEGoodmanWilson** [comment]
Ah, I now understand the difficulty! I was a little lost before.

The problem is that the SDK has no way of knowing _which_ message is a reply to the one you send. So, yes the callbacks and the promises are all about reporting that the message your bot is sending was _delivered_. If you want to get what people type in response to your bot's message, you're going to need to do a lot of interpretation on your own (or using one of many NLPaaS options!). You'll need to listen for messages in the same channel, possibly that include an @-mention of your bot (if in a group channel), and work out for yourself whether the message constitutes a response to your bot.

Welcome to the central problem of conversational UX ;D `node-slack-sdk` is a thin, modestly-opinionated wrapper around the Slack core APIs. You might consider using a more opinionated, bot-specific framework like [BotKit](https://github.com/howdyai/botkit) to achieve your goals?

**Comment by buob** [comment]
Understood.  I think BotKit actually will serve me well.

Thanks for a point in the right direction!

**Comment by DEGoodmanWilson** [comment]
🙇
